#!/bin/bash

export XDG_CONFIG_HOME=$HOME/.config
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/bin:$PATH"

# Start starship prompt and zoxide
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
