#!/bin/bash
# Aliases
# For a full list of active aliases, run `alias`.
#

# Color ls, required exa plugin
alias exa="exa --color=auto --time-style=long-iso"
alias ls="exa"
alias la="ls --long --all --header --icons"
#alias lg="ls --long --all --header --icons --git"
alias fd="fdfind"
alias less="less -R"

alias cz="chezmoi"
alias lg="lazygit"
alias gitui="gitui -t mocha.ron"

alias bat="batcat"
alias cat="bat"

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
